<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-27T20:49:26 AST" name="Default suite" finished-at="2022-11-27T20:49:45 AST" duration-ms="18018">
    <groups>
    </groups>
    <test started-at="2022-11-27T20:49:26 AST" name="Default test" finished-at="2022-11-27T20:49:45 AST" duration-ms="18018">
      <class name="smart_buy.smart_buy">
        <test-method is-config="true" signature="log_in()[pri:0, instance:smart_buy.smart_buy@2e005c4b]" started-at="2022-11-27T20:49:26 AST" name="log_in" finished-at="2022-11-27T20:49:37 AST" duration-ms="10436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- log_in -->
        <test-method signature="adding_items_to_cart()[pri:0, instance:smart_buy.smart_buy@2e005c4b]" started-at="2022-11-27T20:49:37 AST" name="adding_items_to_cart" finished-at="2022-11-27T20:49:43 AST" duration-ms="5898" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adding_items_to_cart -->
        <test-method signature="check_correct_price()[pri:0, instance:smart_buy.smart_buy@2e005c4b]" started-at="2022-11-27T20:49:43 AST" name="check_correct_price" finished-at="2022-11-27T20:49:45 AST" duration-ms="1633" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [1200] but found [269.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1200] but found [269.0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at smart_buy.smart_buy.check_correct_price(smart_buy.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_correct_price -->
      </class> <!-- smart_buy.smart_buy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
